const translations = {
    th: {
        common: {
            schoolName: "โรงเรียนผู้ใหญ่เทศบาลนครนครศรีธรรมราช",
            slogan: "\"เรียนดี มีความสุข\"",
            navHome: "หน้าหลัก HOME",
            navAbout: "เกี่ยวกับ ABOUT US",
            history: "ประวัติความเป็นมา",
            authority: "อำนาจ หน้าที่",
            missionVision: "วิสัยทัศน์ พันธกิจ จุดเน้น",
            staff: "ผู้บริหารและบุคลากร",
            law: "กฎหมายที่เกี่ยวข้อง",
            navNews: "ข่าวสารกิจกรรม NEWS",
            publicNews: "ข่าวประชาสัมพันธ์",
            jobsNews: "ข่าวรับสมัครงาน",
            procurement: "จัดซื้อจัดจ้าง",
            navAchievement: "การดำเนินงาน ACHIEVEMENT",
            navContact: "ติดต่อเรา CONTACT US",
            more: "ดูเพิ่มเติม",
            readMore: "อ่านต่อ",
            details: "ดูรายละเอียด",
            mainMenu: "เมนูหลัก",
            homeShort: "หน้าแรก",
            aboutShort: "เกี่ยวกับเรา",
            activityNewsTitle: "ข่าวสารกิจกรรม",
            achievementShort: "การดำเนินงาน",
            contactShort: "ติดต่อเรา",
            moreInfo: "สอบถามข้อมูลเพิ่มเติม",
            aboutAgency: "เกี่ยวกับหน่วยงาน",
            aboutAgencyText: "องค์กรหลักที่มีหน้าที่รับผิดชอบในการพัฒนาการเรียนรู้และดูแลประชาชนในพื้นที่ ภายใต้แนวทางการบริหารงานของภาครัฐ",
            contactPlace: "สถานที่ติดต่อ",
            address: "โรงเรียนผู้ใหญ่เทศบาลนครนครศรีธรรมราช ตั้งอยู่อาคารศิลปชีพ ชั้น 2 ในสำนักงานเทศบาลนครนครศรีธรรมราช เลขที่ 1082 ถนนราชดำเนิน ตำบลคลัง อำเภอเมืองนครศรีธรรมราช จังหวัดนครศรีธรรมราช",
            copyright: "ลิขสิทธิ์ © 2569 โรงเรียนผู้ใหญ่เทศบาลนครนครศรีธรรมราช. สงวนลิขสิทธิ์.",
            newsCategory: "หมวดข่าว",
            latestNews: "ข่าวล่าสุด",
            commonDocs: "เอกสารที่ใช้บ่อย",
            announcementTypes: "ประเภทประกาศ",
            educationServices: "บริการการศึกษา",
            basicEducation: "การศึกษาขั้นพื้นฐาน",
            continuingEducation: "การศึกษาต่อเนื่อง",
            informalLearning: "การเรียนรู้ตามอัธยาศัย",
            careerGuidance: "แนะแนวและพัฒนาอาชีพ",
            aboutUs: "เกี่ยวกับเรา"
        },
        index: {
            pageTitle: "โรงเรียนผู้ใหญ่เทศบาลนครนครศรีธรรมราช",
            searchTitle: "การค้นหา",
            searchPlaceholder: "คำค้นหา : ชื่อกิจกรรม เอกสาร หรือคำที่เกี่ยวข้อง",
            searchButton: "ค้นหา",
            heroTitle: "นำผู้เรียนเข้าร่วมโครงการประกวดโครงงานวิทยาศาสตร์สำหรับนักศึกษา สกร.",
            noticeTitle: "ประกาศ",
            announceText: "สมัครฟรี ไม่มีค่าใช้จ่าย สอบเทียบวัดระดับความรู้ ครั้งที่ 3 ระดับการศึกษาขั้นพื้นฐาน รับสมัครตั้งแต่วันนี้ถึง 7 กรกฎาคม 2568",
            newsCard1Title: "วันพุธที่ 2 กรกฎาคม 2568 โครงการประกวดโครงงานวิทยาศาสตร์ด้านสิ่งแวดล้อม",
            newsCard1Text: "นำผู้เรียนเข้าร่วมโครงการประกวดโครงงานวิทยาศาสตร์สำหรับนักศึกษา สกร.",
            newsCard2Title: "วันที่ 1 - 2 กรกฎาคม 2568 โครงการอบรมเชิงปฏิบัติการต่อต้านการทุจริต",
            newsCard2Text: "ปลุกจิตสำนึกให้ผู้เรียนและส่งเสริมความรับผิดชอบต่อสังคม",
            newsCard3Title: "วันที่ 1 กรกฎาคม 2568 กิจกรรมวันคล้ายวันสถาปนาคณะลูกเสือแห่งชาติ",
            newsCard3Text: "เข้าร่วมกิจกรรม ณ สนามกีฬาองค์การบริหารส่วนจังหวัดนครศรีธรรมราช",
            miniJob6: "ข่าวการรับสมัครงานตำแหน่งที่ 6",
            miniJob5: "ข่าวการรับสมัครงานตำแหน่งที่ 5",
            miniProc6: "ตัวอย่างประกาศการจัดซื้อจัดจ้างตามรายการที่ 6",
            miniProc5: "ตัวอย่างประกาศการจัดซื้อจัดจ้างตามรายการที่ 5",
            directorName: "นายอาคม กิจการ",
            directorTitle: "ผู้อำนวยการสถานศึกษาโรงเรียนผู้ใหญ่เทศบาลนครนครศรีธรรมราช",
            relatedInfo: "ข้อมูลที่เกี่ยวข้อง",
            basicInfo: "สภาพและข้อมูลพื้นฐาน",
            authorityNoComma: "อำนาจหน้าที่",
            orgStructure: "โครงสร้างองค์กร",
            visionMission: "วิสัยทัศน์ / พันธกิจ",
            officeContact: "ติดต่อสำนักงาน",
            serviceSystems: "ระบบงานบริการ",
            calendarTitle: "ปฏิทินกิจกรรม",
            municipalActivity6: "ข่าวกิจกรรมเทศบาลที่ 6",
            municipalActivity5: "ข่าวกิจกรรมเทศบาลที่ 5",
            municipalActivity4: "ข่าวกิจกรรมเทศบาลที่ 4",
            municipalActivity3: "ข่าวกิจกรรมเทศบาลที่ 3",
            municipalActivity2: "ข่าวกิจกรรมเทศบาลที่ 2",
            downloadsTitle: "เอกสารดาวน์โหลด",
            meetingReport: "รายงานการประชุม",
            meetingReportText: "รายงานการประชุม ครั้งที่ 1/2568",
            forms: "แบบฟอร์ม",
            formsText: "แบบแจ้งข้อมูลการรับเงินโอนผ่านระบบ KTB Corporate Online",
            onlineJournal: "วารสารออนไลน์",
            onlineJournalText: "วารสารเทศบาลเล่มที่ 6 และเอกสารเผยแพร่อื่น ๆ",
            subdistrictCenter: "บริการการศึกษา",
            centerNaiMueang: "การศึกษาขั้นพื้นฐาน",
            centerThaWang: "การศึกษาต่อเนื่อง",
            centerKhlang: "การเรียนรู้ตามอัธยาศัย",
            centerThaRai: "แนะแนวและพัฒนาอาชีพ"
        },
        history: {
            pageTitle: "ประวัติโรงเรียน - โรงเรียนผู้ใหญ่เทศบาลนครนครศรีธรรมราช",
            heroBreadcrumb: "หน้าหลัก / เกี่ยวกับเรา / ประวัติความเป็นมา",
            heroTitle: "ประวัติโรงเรียนผู้ใหญ่เทศบาลนครนครศรีธรรมราช",
            heroText: "สร้างโอกาสทางการศึกษา พัฒนาคุณภาพชีวิต และส่งเสริมการเรียนรู้ตลอดชีวิตให้กับประชาชนในชุมชน",
            headingEyebrow: "ABOUT SCHOOL",
            headingTitle: "ประวัติโรงเรียนผู้ใหญ่เทศบาลนครนครศรีธรรมราช",
            body1: "สังคมยุคโลกาภิวัตน์ทำให้บริบทด้านต่าง ๆ เปลี่ยนแปลง ส่งผลต่อการดำเนินชีวิตในสังคม เมืองกลายเป็นชุมชนแออัด มีเด็กเร่ร่อน เด็กยากไร้ และผู้ขาดโอกาสทางการศึกษา หน่วยงานเทศบาลนครนครศรีธรรมราชจึงให้ความสำคัญกับการศึกษานอกระบบเพื่อสร้างโอกาสและความเสมอภาคให้ประชาชน",
            body2: "การศึกษานอกระบบที่จัดโดยเทศบาลนครนครศรีธรรมราชมีวัตถุประสงค์เพื่อสร้างความเสมอภาคทางการศึกษา ยืดหยุ่นด้านสาระ เวลา และการจัดการเรียนรู้ โดยเน้นการบูรณาการเนื้อหาให้สอดคล้องกับวิถีชีวิต ชุมชน และสังคม",
            objectiveTitle: "วัตถุประสงค์ของโรงเรียน",
            objectiveText: "โรงเรียนผู้ใหญ่เทศบาลนครนครศรีธรรมราช มีวัตถุประสงค์เพื่อสร้างโอกาสทางการศึกษาในชุมชนให้ประชาชนได้พัฒนาตนเอง",
            objective1: "มีความรู้พื้นฐานสำหรับการดำรงชีวิต มีคุณธรรม จริยธรรม ค่านิยมที่ดีงาม และสามารถอยู่ร่วมกันในสังคมอย่างสันติสุข",
            objective2: "นำความรู้ไปประยุกต์ใช้ในการประกอบอาชีพให้สอดคล้องกับความสนใจ ความถนัด และทันต่อความเปลี่ยนแปลงทางเศรษฐกิจ สังคม และการเมือง",
            sideTitle: "โรงเรียนผู้ใหญ่เทศบาลนครนครศรีธรรมราช",
            sideText: "หน่วยงานการศึกษานอกระบบที่มุ่งสร้างความเสมอภาคและโอกาสทางการศึกษาให้กับประชาชนทุกกลุ่ม"
        },
        authority: {
            pageTitle: "อำนาจหน้าที่ - โรงเรียนผู้ใหญ่เทศบาลนครนครศรีธรรมราช",
            heroBreadcrumb: "หน้าหลัก / เกี่ยวกับเรา / อำนาจหน้าที่",
            heroTitle: "อำนาจหน้าที่",
            heroText: "ส่งเสริมความเสมอภาคทางการศึกษา สร้างโอกาสในการเรียนรู้ และตอบสนองความต้องการของประชาชนในเขตเทศบาลนครนครศรีธรรมราช",
            headingTitle: "อำนาจหน้าที่ของโรงเรียน",
            intro: "โรงเรียนผู้ใหญ่เทศบาลนครนครศรีธรรมราช มีบทบาทในการจัดการศึกษาและส่งเสริมการเรียนรู้ให้ประชาชนได้รับโอกาสทางการศึกษาอย่างทั่วถึง โดยมีอำนาจหน้าที่สำคัญดังนี้",
            item1Title: "สร้างความเสมอภาคทางการศึกษา",
            item1Text: "เพื่อสร้างความเสมอภาคทางการศึกษาให้ประชาชนทุกกลุ่มสามารถเข้าถึงการเรียนรู้ได้อย่างเท่าเทียม",
            item2Title: "เพิ่มโอกาสศึกษาต่อ",
            item2Text: "เพื่อให้ผู้ที่พลาดโอกาสทางการศึกษาได้ศึกษาต่อในระดับที่สูงขึ้น และพัฒนาตนเองได้ตามศักยภาพ",
            item3Title: "ส่งเสริมความรู้และทักษะอาชีพ",
            item3Text: "เพื่อส่งเสริมความรู้ พัฒนาทักษะในการประกอบอาชีพ และนำไปประยุกต์ใช้ในชีวิตประจำวัน",
            item4Title: "ตอบสนองความต้องการของประชาชน",
            item4Text: "เพื่อตอบสนองความต้องการของประชาชนในเขตเทศบาลนครนครศรีธรรมราช",
            sideText: "ภารกิจด้านการจัดการศึกษาเพื่อประชาชน ครอบคลุมความเสมอภาค โอกาส ทักษะอาชีพ และการพัฒนาคุณภาพชีวิต"
        },
        laws: {
            pageTitle: "กฎหมายที่เกี่ยวข้อง - โรงเรียนผู้ใหญ่เทศบาลนครนครศรีธรรมราช",
            heroBreadcrumb: "หน้าหลัก / เกี่ยวกับเรา / กฎหมายที่เกี่ยวข้อง",
            heroTitle: "กฎหมายที่เกี่ยวข้อง",
            heroText: "รวบรวมพระราชบัญญัติ กฎกระทรวง คำสั่ง ระเบียบ และประกาศที่เกี่ยวข้องกับการส่งเสริมการเรียนรู้และการดำเนินงานของโรงเรียน",
            headingTitle: "เอกสารกฎหมายและระเบียบที่เกี่ยวข้อง",
            summary1: "หมวดเอกสาร",
            summary2: "รายการเผยแพร่",
            summary3: "ปรับปรุงล่าสุด",
            section1Title: "พระราชบัญญัติ",
            section1Text: "กฎหมายหลักที่ใช้เป็นกรอบการดำเนินงานด้านการส่งเสริมการเรียนรู้",
            law1Title: "พ.ร.บ. ส่งเสริมการเรียนรู้ พ.ศ. 2566",
            law1Text: "พระราชบัญญัติหลักสำหรับการส่งเสริมการเรียนรู้และการศึกษาตลอดชีวิต",
            section2Title: "กฎกระทรวง",
            section2Text: "กฎกระทรวงที่กำหนดโครงสร้าง หน้าที่ และแนวทางการแบ่งส่วนราชการ",
            law2Title: "กฎกระทรวงแบ่งส่วนราชการกรมส่งเสริมการเรียนรู้ กระทรวงศึกษาธิการ พ.ศ. 2567",
            law2Text: "กำหนดการแบ่งส่วนราชการและภารกิจของกรมส่งเสริมการเรียนรู้",
            section3Title: "คำสั่ง ระเบียบ และประกาศ",
            section3Text: "เอกสารแนวปฏิบัติและประกาศราชการที่เกี่ยวข้องกับการบริหารงาน",
            law3Title: "ประกาศกรมส่งเสริมการเรียนรู้ เรื่อง การจัดโครงสร้างการแบ่งงานภายในของส่วนราชการตามกฎกระทรวง",
            law3Text: "แนวทางการจัดโครงสร้างและการแบ่งงานภายในตามกฎกระทรวง พ.ศ. 2567",
            law4Title: "ประกาศกรมส่งเสริมการเรียนรู้ เรื่อง วัฒนธรรมองค์กรของกรมส่งเสริมการเรียนรู้",
            law4Text: "กรอบวัฒนธรรมองค์กรและแนวปฏิบัติในการดำเนินงาน",
            law5Title: "ประกาศสำนักนายกรัฐมนตรี เรื่อง กำหนดภาพเครื่องหมายราชการของกรมส่งเสริมการเรียนรู้",
            law5Text: "ประกาศตามพระราชบัญญัติเครื่องหมายราชการ พุทธศักราช 2482 (ฉบับที่ 332)",
            openDocument: "เปิดเอกสาร",
            sideTitle: "คลังเอกสารกฎหมาย",
            sideText: "ตรวจสอบและเข้าถึงเอกสารที่เกี่ยวข้องกับการดำเนินงานของโรงเรียนได้จากหน้านี้"
        },
        teachers: {
            pageTitle: "ผู้บริหารและบุคลากร - โรงเรียนผู้ใหญ่เทศบาลนครนครศรีธรรมราช",
            heroBreadcrumb: "หน้าหลัก / เกี่ยวกับเรา / ผู้บริหารและบุคลากร",
            heroTitle: "ผู้บริหารและบุคลากร",
            heroText: "ทำเนียบผู้บริหาร ครู และบุคลากรที่ร่วมขับเคลื่อนการเรียนรู้ตลอดชีวิตให้กับประชาชนในพื้นที่",
            headingEyebrow: "ADMINISTRATION",
            headingTitle: "ผู้บริหารสถานศึกษา",
            directorName: "นายอาคม กิจการ",
            directorTitle: "ผู้อำนวยการสถานศึกษา โรงเรียนผู้ใหญ่เทศบาลนครนครศรีธรรมราช",
            groupDistrict: "บุคลากร",
            groupSubdistrict: "ครู ศกร.ตำบล",
            person1Name: "นางสาวอัญชิสา ขนอม",
            person1Role: "งานการศึกษานอกระบบขั้นพื้นฐานระดับชั้น มัธยมต้น",
            person2Name: "นางสาวสุดารัตน์ ไชยรัตน์",
            person2Role: "ตำแหน่ง ธุรการ",
            person2tag: "งานการศึกษานอกระบบขั้นพื้นฐาน",
            person3Name: "นางสาวสุดารัตน์ วัฒนประเสริฐกุล",
            person3Role: "งานการศึกษานอกระบบขั้นพื้นฐานระดับชั้น มัธยมปลาย",
            person4Name: "นางสาวกมลชนก เพชรแก้ว",
            person4Role: "ครู ศกร.ตำบลในเมือง",
            person5Name: "นายกิตติพงศ์ นาคช่วย",
            person5Role: "ครู ศกร.ตำบลท่าวัง",
            person6Name: "นางสาวสุภาภรณ์ รัตนเดช",
            person6Role: "ครู ศกร.ตำบลคลัง",
            person7Name: "นายภาณุพงศ์ ชูช่วย",
            person7Role: "ครู ศกร.ตำบลท่าไร่",
            person8Name: "นางสาววรรณวิสา แก้วมณี",
            person8Role: "ครู ศกร.ตำบลปากนคร",
            person9Name: "นายอนุชา ทองมาก",
            person9Role: "ครูผู้ช่วยงานส่งเสริมอาชีพ"
        },
        mission: {
            pageTitle: "วิสัยทัศน์และพันธกิจ - โรงเรียนผู้ใหญ่เทศบาลนครนครศรีธรรมราช",
            heroBreadcrumb: "หน้าหลัก / เกี่ยวกับเรา / วิสัยทัศน์และพันธกิจ",
            heroTitle: "วิสัยทัศน์และพันธกิจ",
            heroText: "มุ่งสร้างความรู้ ควบคู่ทักษะอาชีพ เทคโนโลยี ความพอเพียง และการบริหารแบบมีส่วนร่วม",
            headingTitle: "วิสัยทัศน์โรงเรียน",
            visionLabel: "วิสัยทัศน์",
            visionText: "เป็นผู้นำการสร้างโอกาสทางการศึกษาที่เท่าเทียม ด้วยนวัตกรรมการเรียนรู้เชิงรุก ผสานความร่วมมือภาคีเครือข่าย เพื่อยกระดับคุณภาพชีวิตอย่างยั่งยืน",
            missionHeading: "พันธกิจ",
            mission1Title: "รุกเข้าถึงชุมชน (Active Outreach)",
            mission1Text: "จัดการเรียนการสอนหลักสูตรส่งเสริมการเรียนรู้ระดับการศึกษาขั้นพื้นฐาน พุทธศักราช 2566",
            mission1Note: "ปีการศึกษา 2568 ระดับมัธยมศึกษาตอนต้น จำนวน 60 คน และระดับมัธยมศึกษาตอนปลาย จำนวน 58 คน",
            mission2Title: "ขยายความเท่าเทียม (Educational Equity)",
            mission2Text: "เด็ก เยาวชน และประชาชนในเขตเทศบาลนครนครศรีธรรมราชที่พลาดโอกาสทางการศึกษา สามารถได้รับการศึกษานอกระบบทั้งระดับมัธยมศึกษาตอนต้นและตอนปลาย",
            mission3Title: "ผนึกกำลังภาคีเครือข่าย (Synergistic Partnership)",
            mission3Text: "จัดประชุม อบรม สัมมนา และพัฒนาบุคลากร เพื่อยกระดับคุณภาพการจัดการศึกษาและบริการประชาชน",
            mission4Title: "ยกระดับคุณภาพชีวิต (Life Enhancement)",
            mission4Text: "จัดประชุม อบรม สัมมนา และพัฒนาบุคลากร เพื่อยกระดับคุณภาพการจัดการศึกษาและบริการประชาชน",
            sideText: "แนวทางการพัฒนาผู้เรียนให้มีความรู้ ทักษะอาชีพ ใช้เทคโนโลยีอย่างเหมาะสม และดำรงชีวิตตามหลักความพอเพียง"
        },
        news: {
            pageTitle: "ข่าวประชาสัมพันธ์ - โรงเรียนผู้ใหญ่เทศบาลนครนครศรีธรรมราช",
            heroBreadcrumb: "หน้าหลัก / ข่าวสารกิจกรรม / ข่าวประชาสัมพันธ์",
            heroTitle: "ข่าวประชาสัมพันธ์",
            heroText: "ข่าวสาร กิจกรรม และประกาศทั่วไปของโรงเรียน สำหรับนักศึกษา ผู้ปกครอง และประชาชน",
            listTitle: "รายการข่าวประชาสัมพันธ์",
            searchPlaceholder: "ค้นหาข่าวประชาสัมพันธ์",
            featured: "ข่าวเด่น",
            featureTitle: "ปฐมนิเทศนักศึกษาใหม่ ภาคเรียนที่ 1 ปีการศึกษา 2569",
            featureText: "โรงเรียนจัดกิจกรรมปฐมนิเทศเพื่อชี้แจงแนวทางการเรียน การวัดผล และบริการสนับสนุนนักศึกษา พร้อมเปิดระบบติดตามผลการเรียนออนไลน์",
            featureMeta: "12 พฤษภาคม 2569 | งานประชาสัมพันธ์",
            row1Badge: "กิจกรรม",
            row1Title: "อบรมทักษะดิจิทัลสำหรับนักศึกษาผู้ใหญ่",
            row1Text: "เสริมความรู้การใช้แอปพลิเคชันเพื่อการเรียนรู้ การค้นคว้า และการประกอบอาชีพในชีวิตประจำวัน",
            row1Meta: "8 พฤษภาคม 2569 | กลุ่มงานการศึกษาต่อเนื่อง",
            row2Badge: "ประกาศ",
            row2Title: "ประกาศตารางสอบปลายภาค ภาคเรียนที่ 1 ปีการศึกษา 2569",
            row2Text: "แจ้งกำหนดการสอบ รายวิชา ห้องสอบ และแนวปฏิบัติสำหรับนักศึกษาทุกระดับชั้น",
            row2Meta: "3 พฤษภาคม 2569 | งานทะเบียนและวัดผล",
            row3Badge: "อบรมอาชีพ",
            row3Title: "เปิดรับสมัครโครงการฝึกอาชีพระยะสั้น การทำผลิตภัณฑ์ชุมชน",
            row3Text: "รับสมัครประชาชนที่สนใจพัฒนาทักษะอาชีพและสร้างรายได้เสริม สมัครได้ถึงวันที่ 25 พฤษภาคม 2569",
            row3Meta: "1 พฤษภาคม 2569 | งานส่งเสริมอาชีพ"
        },
        jobs: {
            pageTitle: "ข่าวรับสมัครงาน - โรงเรียนผู้ใหญ่เทศบาลนครนครศรีธรรมราช",
            heroBreadcrumb: "หน้าหลัก / ข่าวสารกิจกรรม / ข่าวรับสมัครงาน",
            heroTitle: "ข่าวรับสมัครงาน",
            heroText: "ประกาศรับสมัครบุคลากร ครูผู้สอน วิทยากร และเจ้าหน้าที่สนับสนุนงานการศึกษา",
            listTitle: "รายการรับสมัครงาน",
            searchPlaceholder: "ค้นหาตำแหน่งงาน",
            statusOpen: "เปิดรับสมัคร",
            statusClosed: "ปิดรับสมัคร",
            job1Title: "ครูอัตราจ้าง วิชาเทคโนโลยีดิจิทัล",
            job1Text: "จำนวน 1 อัตรา ปฏิบัติงานด้านการจัดการเรียนการสอนและพัฒนาสื่อออนไลน์สำหรับนักศึกษาผู้ใหญ่",
            job1Meta1: "รับสมัคร: 10-24 พฤษภาคม 2569",
            job1Meta2: "คุณวุฒิ: ปริญญาตรีสาขาที่เกี่ยวข้อง",
            job2Title: "วิทยากรหลักสูตรอาชีพระยะสั้น",
            job2Text: "รับสมัครวิทยากรด้านอาหาร งานหัตถกรรม และการตลาดออนไลน์ เพื่อจัดอบรมให้ประชาชนในพื้นที่",
            job2Meta1: "รับสมัคร: 15-30 พฤษภาคม 2569",
            job2Meta2: "คุณสมบัติ: มีประสบการณ์สอนหรือประกอบอาชีพจริง",
            job3Title: "เจ้าหน้าที่ธุรการโครงการส่งเสริมการเรียนรู้",
            job3Text: "สนับสนุนงานเอกสาร ประสานงานผู้เรียน และจัดทำรายงานผลการดำเนินงานประจำเดือน",
            job3Meta1: "รับสมัคร: 1-9 พฤษภาคม 2569",
            job3Meta2: "สถานะ: อยู่ระหว่างตรวจสอบคุณสมบัติ",
            viewAnnouncement: "ดูประกาศ",
            doc1: "ใบสมัครงาน",
            doc2: "แบบรับรองคุณสมบัติ",
            doc3: "รายการเอกสารประกอบการสมัคร"
        },
        procurement: {
            pageTitle: "จัดซื้อจัดจ้าง - โรงเรียนผู้ใหญ่เทศบาลนครนครศรีธรรมราช",
            heroBreadcrumb: "หน้าหลัก / ข่าวสารกิจกรรม / จัดซื้อจัดจ้าง",
            heroTitle: "จัดซื้อจัดจ้าง",
            heroText: "ประกาศแผนจัดซื้อจัดจ้าง ราคากลาง ผลการพิจารณา และเอกสารที่เกี่ยวข้องอย่างโปร่งใส",
            listTitle: "รายการประกาศจัดซื้อจัดจ้าง",
            searchPlaceholder: "ค้นหาเลขที่ประกาศหรือรายการ",
            tableDate: "วันที่",
            tableNo: "เลขที่ประกาศ",
            tableItem: "รายการ",
            tableType: "ประเภท",
            tableStatus: "สถานะ",
            row1Date: "14 พ.ค. 2569",
            row1No: "พญ. 03/2569",
            row1Item: "จัดซื้อวัสดุการเรียนการสอนสำหรับภาคเรียนที่ 1/2569",
            row1Type: "ประกาศราคากลาง",
            row1Status: "เผยแพร่",
            row2Date: "9 พ.ค. 2569",
            row2No: "พญ. 02/2569",
            row2Item: "จ้างปรับปรุงระบบเครือข่ายอินเทอร์เน็ตห้องเรียนคอมพิวเตอร์",
            row2Type: "ประกาศเชิญชวน",
            row2Status: "รับข้อเสนอ",
            row3Date: "2 พ.ค. 2569",
            row3No: "พญ. 01/2569",
            row3Item: "ประกาศผู้ชนะการเสนอราคาจ้างผลิตสื่อประชาสัมพันธ์รับสมัครนักศึกษา",
            row3Type: "ประกาศผู้ชนะ",
            row3Status: "เสร็จสิ้น",
            row4Date: "25 เม.ย. 2569",
            row4No: "ผจ. 06/2569",
            row4Item: "แผนจัดซื้อครุภัณฑ์สำนักงานและอุปกรณ์สนับสนุนการเรียนรู้",
            row4Type: "แผนจัดซื้อจัดจ้าง",
            row4Status: "เผยแพร่แล้ว",
            type1: "แผนจัดซื้อจัดจ้าง",
            type2: "ประกาศราคากลาง",
            type3: "ประกาศเชิญชวน",
            type4: "ประกาศผู้ชนะ"
        },
        contact: {
            pageTitle: "ติดต่อเรา - โรงเรียนผู้ใหญ่เทศบาลนครนครศรีธรรมราช",
            breadcrumb: "คุณอยู่ที่: หน้าแรก / ติดต่อเรา",
            headingTitle: "ติดต่อเรา",
            locationLabel: "สถานที่ติดต่อ :",
            locationText: "โรงเรียนผู้ใหญ่เทศบาลนครนครศรีธรรมราช ตั้งอยู่อาคารศิลปชีพ ชั้น 2 ในสำนักงานเทศบาลนครนครศรีธรรมราช เลขที่ 1082 ถนนราชดำเนิน ตำบลคลัง อำเภอเมืองนครศรีธรรมราช จังหวัดนครศรีธรรมราช",
            addressLabel: "ที่อยู่",
            addressLine: "เลขที่ 1082 ถนนราชดำเนิน",
            addressText: "ตำบลคลัง อำเภอเมืองนครศรีธรรมราช จังหวัดนครศรีธรรมราช",
            hoursLabel: "เวลาทำการ",
            hoursDay: "จันทร์ - ศุกร์",
            hoursTime: "08.30 - 16.30 น.",
            channelLabel: "ช่องทางการติดต่อ :",
            phone: "โทรศัพท์ : -",
            email: "อีเมล : -",
            requiredNote: "All fields with * are required",
            nameLabel: "ชื่อ - นามสกุล",
            emailLabel: "อีเมล",
            subjectLabel: "หัวข้อ",
            messageLabel: "ข้อความ",
            submit: "ส่งข้อความ"
        }
    },
    en: {}
};

translations.en.common = {
    schoolName: "Nakhon Si Thammarat Municipality Adult School",
    slogan: "\"Good Learning, Happy Life\"",
    navHome: "Home",
    navAbout: "About Us",
    history: "History",
    authority: "Authority and Duties",
    missionVision: "Vision, Mission and Focus",
    staff: "Administrators and Staff",
    law: "Related Laws",
    navNews: "News and Activities",
    publicNews: "Public Relations News",
    jobsNews: "Job Announcements",
    procurement: "Procurement",
    navAchievement: "Achievements",
    navContact: "Contact Us",
    more: "View More",
    readMore: "Read More",
    details: "View Details",
    mainMenu: "Main Menu",
    homeShort: "Home",
    aboutShort: "About Us",
    activityNewsTitle: "News and Activities",
    achievementShort: "Achievements",
    contactShort: "Contact Us",
    moreInfo: "More Information",
    aboutAgency: "About the Agency",
    aboutAgencyText: "The main organization responsible for developing learning and supporting people in the local area under public administration guidelines.",
    contactPlace: "Contact Location",
    address: "Nakhon Si Thammarat Provincial Public Library, 2nd Floor, Sanam Na Mueang, Ratchadamnoen Road, Khlang Subdistrict, Mueang Nakhon Si Thammarat District, Nakhon Si Thammarat 80000",
    copyright: "Copyright © 2026 Nakhon Si Thammarat Municipality Adult School. All rights reserved.",
    newsCategory: "News Categories",
    latestNews: "Latest News",
    commonDocs: "Common Documents",
    announcementTypes: "Announcement Types",
    educationServices: "Education Services",
    basicEducation: "Basic Education",
    continuingEducation: "Continuing Education",
    informalLearning: "Informal Learning",
    careerGuidance: "Career Guidance and Development",
    aboutUs: "About Us"
};

translations.en.index = {
    pageTitle: "Nakhon Si Thammarat Municipality Adult School",
    searchTitle: "Search",
    searchPlaceholder: "Keyword: activity name, document, or related term",
    searchButton: "Search",
    heroTitle: "Students joined the science project competition for ONIE learners.",
    noticeTitle: "Announcement",
    announceText: "Free registration for the 3rd basic education equivalency assessment. Applications are open now through July 7, 2025.",
    newsCard1Title: "Wednesday, July 2, 2025: Environmental science project competition",
    newsCard1Text: "Students participated in the science project competition for ONIE learners.",
    newsCard2Title: "July 1 - 2, 2025: Anti-corruption workshop",
    newsCard2Text: "Building awareness and encouraging social responsibility among learners.",
    newsCard3Title: "July 1, 2025: National Scout Day activity",
    newsCard3Text: "Joined the activity at Nakhon Si Thammarat Provincial Administrative Organization Stadium.",
    miniJob6: "Job announcement item 6",
    miniJob5: "Job announcement item 5",
    miniProc6: "Procurement announcement sample item 6",
    miniProc5: "Procurement announcement sample item 5",
    directorName: "Ms. Chutima Klamklai",
    directorTitle: "Director of Nakhon Si Thammarat Municipality Adult School",
    relatedInfo: "Related Information",
    basicInfo: "Basic Information",
    authorityNoComma: "Authority and Duties",
    orgStructure: "Organization Structure",
    visionMission: "Vision / Mission",
    officeContact: "Office Contact",
    serviceSystems: "Service Systems",
    calendarTitle: "Activity Calendar",
    municipalActivity6: "Municipal activity news 6",
    municipalActivity5: "Municipal activity news 5",
    municipalActivity4: "Municipal activity news 4",
    municipalActivity3: "Municipal activity news 3",
    municipalActivity2: "Municipal activity news 2",
    downloadsTitle: "Downloads",
    meetingReport: "Meeting Reports",
    meetingReportText: "Meeting report No. 1/2025",
    forms: "Forms",
    formsText: "KTB Corporate Online transfer information form",
    onlineJournal: "Online Journal",
    onlineJournalText: "Municipal journal issue 6 and other publications",
    subdistrictCenter: "Subdistrict Learning Centers",
    centerNaiMueang: "Nai Mueang Subdistrict Learning Center",
    centerThaWang: "Tha Wang Subdistrict Learning Center",
    centerKhlang: "Khlang Subdistrict Learning Center",
    centerThaRai: "Tha Rai Subdistrict Learning Center",
    centerPakNakhon: "Pak Nakhon Subdistrict Learning Center"
};

Object.assign(translations.en, {
    history: {
        pageTitle: "School History - Nakhon Si Thammarat Municipality Adult School",
        heroBreadcrumb: "Home / About Us / History",
        heroTitle: "History of Nakhon Si Thammarat Municipality Adult School",
        heroText: "Creating educational opportunity, improving quality of life, and supporting lifelong learning for people in the community.",
        headingEyebrow: "ABOUT SCHOOL",
        headingTitle: "History of Nakhon Si Thammarat Municipality Adult School",
        body1: "Global changes have affected daily life and community conditions. Urban communities face crowding, vulnerable youth, poverty, and unequal access to education. Nakhon Si Thammarat Municipality therefore gives importance to non-formal education as a path toward opportunity and equity.",
        body2: "The municipality's non-formal education is designed to create educational equality with flexible content, schedules, and learning management. It integrates learning with real life, local communities, and society.",
        objectiveTitle: "School Objectives",
        objectiveText: "The school aims to create educational opportunities in the community so learners can continue developing themselves.",
        objective1: "Provide fundamental knowledge for living, with morality, ethics, positive values, and peaceful coexistence.",
        objective2: "Apply knowledge to careers in ways that match interests, abilities, and economic, social, and civic change.",
        sideTitle: "Nakhon Si Thammarat Municipality Adult School",
        sideText: "A non-formal education organization focused on equity and educational opportunity for all groups of people."
    },
    authority: {
        pageTitle: "Authority and Duties - Nakhon Si Thammarat Municipality Adult School",
        heroBreadcrumb: "Home / About Us / Authority and Duties",
        heroTitle: "Authority and Duties",
        heroText: "Promoting educational equality, creating learning opportunities, and responding to the needs of people in Nakhon Si Thammarat Municipality.",
        headingTitle: "School Authority and Duties",
        intro: "The school has a role in providing education and promoting learning so people can access educational opportunity widely. Its key duties are as follows.",
        item1Title: "Create educational equality",
        item1Text: "Enable all groups of people to access learning opportunities equally.",
        item2Title: "Increase opportunities for further study",
        item2Text: "Support people who missed educational opportunities to continue studying and develop their potential.",
        item3Title: "Promote knowledge and career skills",
        item3Text: "Build knowledge and career skills that can be applied in everyday life.",
        item4Title: "Respond to community needs",
        item4Text: "Respond to the needs of people in Nakhon Si Thammarat Municipality.",
        sideText: "Education services for the public, covering equality, opportunity, career skills, and quality of life."
    },
    laws: {
        pageTitle: "Related Laws - Nakhon Si Thammarat Municipality Adult School",
        heroBreadcrumb: "Home / About Us / Related Laws",
        heroTitle: "Related Laws",
        heroText: "A collection of acts, ministerial regulations, orders, rules, and announcements related to learning promotion and school operations.",
        headingTitle: "Related Legal and Regulatory Documents",
        summary1: "Document Categories",
        summary2: "Published Items",
        summary3: "Latest Update",
        section1Title: "Acts",
        section1Text: "Core laws used as the framework for learning promotion operations.",
        law1Title: "Learning Promotion Act B.E. 2566",
        law1Text: "The main act for promoting learning and lifelong education.",
        section2Title: "Ministerial Regulations",
        section2Text: "Regulations defining structure, duties, and administrative divisions.",
        law2Title: "Ministerial Regulation on Administrative Division of the Department of Learning Promotion, Ministry of Education B.E. 2567",
        law2Text: "Defines administrative divisions and responsibilities of the Department of Learning Promotion.",
        section3Title: "Orders, Rules and Announcements",
        section3Text: "Operational guidance and official announcements related to administration.",
        law3Title: "Department of Learning Promotion announcement on internal work structure under the ministerial regulation",
        law3Text: "Guidelines for internal structure and work division under the 2024 ministerial regulation.",
        law4Title: "Department of Learning Promotion announcement on organizational culture",
        law4Text: "Organizational culture framework and operational practices.",
        law5Title: "Prime Minister's Office announcement on the official emblem of the Department of Learning Promotion",
        law5Text: "Announcement under the Official Emblem Act B.E. 2482, No. 332.",
        openDocument: "Open Document",
        sideTitle: "Legal Document Library",
        sideText: "Access documents related to the school's operations from this page."
    },
    teachers: {
        pageTitle: "Administrators and Staff - Nakhon Si Thammarat Municipality Adult School",
        heroBreadcrumb: "Home / About Us / Administrators and Staff",
        heroTitle: "Administrators and Staff",
        heroText: "A directory of administrators, teachers, and staff who support lifelong learning for people in the local area.",
        headingEyebrow: "ADMINISTRATION",
        headingTitle: "School Administration",
        directorName: "Ms. Chutima Klamklai",
        directorTitle: "Director of Mueang Nakhon Si Thammarat District Learning Promotion Center",
        groupDistrict: "District Personnel",
        groupSubdistrict: "Subdistrict Learning Center Teachers",
        person1Name: "Mr. Somchai Jaidee",
        person1Role: "Non-formal education volunteer teacher",
        person2Name: "Ms. Paweena Saengthong",
        person2Role: "Administrative position",
        person2tag: "Basic education curriculum teacher",
        person3Name: "Mr. Thanaphon Srisuk",
        person3Role: "Registration and assessment officer",
        person4Name: "Ms. Kamonchanok Phetkaew",
        person4Role: "Nai Mueang Subdistrict Learning Center teacher",
        person5Name: "Mr. Kittiphong Nakchuay",
        person5Role: "Tha Wang Subdistrict Learning Center teacher",
        person6Name: "Ms. Supaporn Rattanadet",
        person6Role: "Khlang Subdistrict Learning Center teacher",
        person7Name: "Mr. Phanuphong Chuchuay",
        person7Role: "Tha Rai Subdistrict Learning Center teacher",
        person8Name: "Ms. Wanwisa Kaewmani",
        person8Role: "Pak Nakhon Subdistrict Learning Center teacher",
        person9Name: "Mr. Anucha Thongmak",
        person9Role: "Career promotion assistant teacher"
    },
    mission: {
        pageTitle: "Vision and Mission - Nakhon Si Thammarat Municipality Adult School",
        heroBreadcrumb: "Home / About Us / Vision and Mission",
        heroTitle: "Vision and Mission",
        heroText: "Building knowledge with career skills, technology, sufficiency, and participatory administration.",
        headingTitle: "School Vision",
        visionLabel: "Vision",
        visionText: "Build knowledge with careers, advance with technology, live with sufficiency, and administer through participation.",
        missionHeading: "Mission",
        mission1Title: "Provide learning promotion curriculum instruction",
        mission1Text: "Provide basic education learning promotion curriculum instruction under B.E. 2566.",
        mission1Note: "Academic year 2025: 60 lower secondary learners and 58 upper secondary learners.",
        mission2Title: "Open opportunities for people who missed education",
        mission2Text: "Children, youth, and people in the municipality who missed educational opportunities can receive non-formal lower and upper secondary education.",
        mission3Title: "Continuously develop personnel",
        mission3Text: "Organize meetings, training, seminars, and staff development to improve education management and public service quality.",
        sideText: "A development direction for learners to gain knowledge, career skills, appropriate technology use, and sufficiency-based living."
    },
    news: {
        pageTitle: "Public Relations News - Nakhon Si Thammarat Municipality Adult School",
        heroBreadcrumb: "Home / News and Activities / Public Relations News",
        heroTitle: "Public Relations News",
        heroText: "School news, activities, and general announcements for students, parents, and the public.",
        listTitle: "Public Relations News List",
        searchPlaceholder: "Search public relations news",
        featured: "Featured",
        featureTitle: "Orientation for New Students, Semester 1 Academic Year 2026",
        featureText: "The school organized orientation to explain learning guidelines, assessment, and student support services, together with the online learning progress system.",
        featureMeta: "May 12, 2026 | Public Relations",
        row1Badge: "Activity",
        row1Title: "Digital skills training for adult students",
        row1Text: "Strengthening application skills for learning, research, and everyday career development.",
        row1Meta: "May 8, 2026 | Continuing Education Unit",
        row2Badge: "Announcement",
        row2Title: "Final exam schedule for Semester 1 Academic Year 2026",
        row2Text: "Exam dates, subjects, rooms, and practice guidelines for students at every level.",
        row2Meta: "May 3, 2026 | Registration and Assessment",
        row3Badge: "Career Training",
        row3Title: "Short course registration: community product making",
        row3Text: "Open for people interested in career skills and supplementary income. Applications close May 25, 2026.",
        row3Meta: "May 1, 2026 | Career Promotion"
    },
    jobs: {
        pageTitle: "Job Announcements - Nakhon Si Thammarat Municipality Adult School",
        heroBreadcrumb: "Home / News and Activities / Job Announcements",
        heroTitle: "Job Announcements",
        heroText: "Recruitment notices for personnel, teachers, trainers, and education support staff.",
        listTitle: "Recruitment List",
        searchPlaceholder: "Search positions",
        statusOpen: "Open",
        statusClosed: "Closed",
        job1Title: "Contract Teacher: Digital Technology",
        job1Text: "One position responsible for teaching and developing online media for adult learners.",
        job1Meta1: "Application period: May 10-24, 2026",
        job1Meta2: "Qualification: Bachelor's degree in a related field",
        job2Title: "Short Career Course Trainer",
        job2Text: "Recruiting trainers in food, handicrafts, and online marketing to provide community training.",
        job2Meta1: "Application period: May 15-30, 2026",
        job2Meta2: "Qualification: Real teaching or professional experience",
        job3Title: "Administrative Officer for Learning Promotion Project",
        job3Text: "Support documents, learner coordination, and monthly performance reporting.",
        job3Meta1: "Application period: May 1-9, 2026",
        job3Meta2: "Status: Qualification review in progress",
        viewAnnouncement: "View Announcement",
        doc1: "Job application form",
        doc2: "Qualification certification form",
        doc3: "Application document checklist"
    },
    procurement: {
        pageTitle: "Procurement - Nakhon Si Thammarat Municipality Adult School",
        heroBreadcrumb: "Home / News and Activities / Procurement",
        heroTitle: "Procurement",
        heroText: "Transparent publication of procurement plans, reference prices, selection results, and related documents.",
        listTitle: "Procurement Announcements",
        searchPlaceholder: "Search announcement number or item",
        tableDate: "Date",
        tableNo: "Announcement No.",
        tableItem: "Item",
        tableType: "Type",
        tableStatus: "Status",
        row1Date: "May 14, 2026",
        row1No: "PY 03/2026",
        row1Item: "Purchase of teaching materials for Semester 1/2026",
        row1Type: "Reference price announcement",
        row1Status: "Published",
        row2Date: "May 9, 2026",
        row2No: "PY 02/2026",
        row2Item: "Computer classroom internet network improvement",
        row2Type: "Invitation announcement",
        row2Status: "Receiving proposals",
        row3Date: "May 2, 2026",
        row3No: "PY 01/2026",
        row3Item: "Winner announcement for student recruitment media production",
        row3Type: "Winner announcement",
        row3Status: "Completed",
        row4Date: "Apr 25, 2026",
        row4No: "PJ 06/2026",
        row4Item: "Procurement plan for office equipment and learning support tools",
        row4Type: "Procurement plan",
        row4Status: "Published",
        type1: "Procurement plan",
        type2: "Reference price announcement",
        type3: "Invitation announcement",
        type4: "Winner announcement"
    },
    contact: {
        pageTitle: "Contact Us - Nakhon Si Thammarat Municipality Adult School",
        breadcrumb: "You are here: Home / Contact Us",
        headingTitle: "Contact Us",
        locationLabel: "Contact location:",
        locationText: "Nakhon Si Thammarat Municipality Adult School is located on the 2nd floor of the Arts and Vocational Building in Nakhon Si Thammarat Municipality Office, 1082 Ratchadamnoen Road, Khlang Subdistrict, Mueang Nakhon Si Thammarat District, Nakhon Si Thammarat.",
        addressLabel: "Address",
        addressLine: "1082 Ratchadamnoen Road",
        addressText: "Khlang Subdistrict, Mueang Nakhon Si Thammarat District, Nakhon Si Thammarat",
        hoursLabel: "Office Hours",
        hoursDay: "Monday - Friday",
        hoursTime: "08:30 - 16:30",
        channelLabel: "Contact channels:",
        phone: "Phone: -",
        email: "Email: -",
        requiredNote: "All fields with * are required",
        nameLabel: "Full Name",
        emailLabel: "Email",
        subjectLabel: "Subject",
        messageLabel: "Message",
        submit: "Send Message"
    }
});

const commonBindings = [
    [".brand h1", "common.schoolName"],
    [".nav > a:nth-of-type(1)", "common.navHome"],
    [".nav .dropdown:nth-of-type(1) > button", "common.navAbout"],
    [".nav .dropdown:nth-of-type(1) .dropdown-menu a:nth-child(1)", "common.history"],
    [".nav .dropdown:nth-of-type(1) .dropdown-menu a:nth-child(2)", "common.authority"],
    [".nav .dropdown:nth-of-type(1) .dropdown-menu a:nth-child(3)", "common.missionVision"],
    [".nav .dropdown:nth-of-type(1) .dropdown-menu a:nth-child(4)", "common.staff"],
    [".nav .dropdown:nth-of-type(1) .dropdown-menu a:nth-child(5)", "common.law"],
    [".nav .dropdown:nth-of-type(2) > button", "common.navNews"],
    [".nav .dropdown:nth-of-type(2) .dropdown-menu a:nth-child(1)", "common.publicNews"],
    [".nav .dropdown:nth-of-type(2) .dropdown-menu a:nth-child(2)", "common.jobsNews"],
    [".nav .dropdown:nth-of-type(2) .dropdown-menu a:nth-child(3)", "common.procurement"],
    [".nav > a:nth-of-type(2)", "common.navAchievement"],
    [".nav > a:nth-of-type(3)", "common.navContact"],
    [".footer-top h3:first-of-type", "common.schoolName"],
    [".qr h3", "common.moreInfo"],
    [".footer-grid > div:nth-child(1) h3", "common.aboutAgency"],
    [".footer-grid > div:nth-child(1) p", "common.aboutAgencyText"],
    [".footer-grid > div:nth-child(2) h3", "common.mainMenu"],
    [".footer-grid > div:nth-child(2) li:nth-child(1)", "common.homeShort"],
    [".footer-grid > div:nth-child(2) li:nth-child(2)", "common.aboutShort"],
    [".footer-grid > div:nth-child(2) li:nth-child(3)", "common.activityNewsTitle"],
    [".footer-grid > div:nth-child(2) li:nth-child(4)", "common.achievementShort"],
    [".footer-grid > div:nth-child(2) li:nth-child(5) a", "common.contactShort"],
    [".footer-grid > div:nth-child(3) h3", "common.educationServices"],
    [".footer-grid > div:nth-child(3) li:nth-child(1)", "common.basicEducation"],
    [".footer-grid > div:nth-child(3) li:nth-child(2)", "common.continuingEducation"],
    [".footer-grid > div:nth-child(3) li:nth-child(3)", "common.informalLearning"],
    [".footer-grid > div:nth-child(3) li:nth-child(4)", "common.careerGuidance"],
    [".footer-grid > div:nth-child(4) h3", "common.contactPlace"],
    [".footer-grid > div:nth-child(4) p", "common.address"],
    [".copyright", "common.copyright"]
];

const pageBindings = {
    history: [
        [".page-hero .breadcrumb", "history.heroBreadcrumb"],
        [".page-hero h2", "history.heroTitle"],
        [".page-hero p", "history.heroText"],
        [".history-content .history-heading span", "history.headingEyebrow"],
        [".history-content .history-heading h2", "history.headingTitle"],
        [".history-content > p:nth-of-type(1)", "history.body1"],
        [".history-content > p:nth-of-type(2)", "history.body2"],
        [".objective-box h3", "history.objectiveTitle"],
        [".objective-box p", "history.objectiveText"],
        [".objective-box li:nth-child(1)", "history.objective1"],
        [".objective-box li:nth-child(2)", "history.objective2"],
        [".history-card h3", "history.sideTitle"],
        [".history-card p", "history.sideText"],
        [".history-menu h3", "common.aboutUs"]
    ],
    authority: [
        [".page-hero .breadcrumb", "authority.heroBreadcrumb"],
        [".page-hero h2", "authority.heroTitle"],
        [".page-hero p", "authority.heroText"],
        [".history-content .history-heading h2", "authority.headingTitle"],
        [".authority-intro", "authority.intro"],
        [".authority-item:nth-child(1) h3", "authority.item1Title"],
        [".authority-item:nth-child(1) p", "authority.item1Text"],
        [".authority-item:nth-child(2) h3", "authority.item2Title"],
        [".authority-item:nth-child(2) p", "authority.item2Text"],
        [".authority-item:nth-child(3) h3", "authority.item3Title"],
        [".authority-item:nth-child(3) p", "authority.item3Text"],
        [".authority-item:nth-child(4) h3", "authority.item4Title"],
        [".authority-item:nth-child(4) p", "authority.item4Text"],
        [".history-card h3", "authority.heroTitle"],
        [".history-card p", "authority.sideText"],
        [".history-menu h3", "common.aboutUs"]
    ],
    laws: [
        [".page-hero .breadcrumb", "laws.heroBreadcrumb"],
        [".page-hero h2", "laws.heroTitle"],
        [".page-hero p", "laws.heroText"],
        [".history-content .history-heading h2", "laws.headingTitle"],
        [".laws-summary div:nth-child(1) span", "laws.summary1"],
        [".laws-summary div:nth-child(2) span", "laws.summary2"],
        [".laws-summary div:nth-child(3) span", "laws.summary3"],
        [".law-section:nth-of-type(1) h3", "laws.section1Title"],
        [".law-section:nth-of-type(1) .law-section-head p", "laws.section1Text"],
        [".law-section:nth-of-type(1) .law-item h4", "laws.law1Title"],
        [".law-section:nth-of-type(1) .law-item p", "laws.law1Text"],
        [".law-section:nth-of-type(2) h3", "laws.section2Title"],
        [".law-section:nth-of-type(2) .law-section-head p", "laws.section2Text"],
        [".law-section:nth-of-type(2) .law-item h4", "laws.law2Title"],
        [".law-section:nth-of-type(2) .law-item p", "laws.law2Text"],
        [".law-section:nth-of-type(3) h3", "laws.section3Title"],
        [".law-section:nth-of-type(3) .law-section-head p", "laws.section3Text"],
        [".law-section:nth-of-type(3) .law-item:nth-child(1) h4", "laws.law3Title"],
        [".law-section:nth-of-type(3) .law-item:nth-child(1) p", "laws.law3Text"],
        [".law-section:nth-of-type(3) .law-item:nth-child(2) h4", "laws.law4Title"],
        [".law-section:nth-of-type(3) .law-item:nth-child(2) p", "laws.law4Text"],
        [".law-section:nth-of-type(3) .law-item:nth-child(3) h4", "laws.law5Title"],
        [".law-section:nth-of-type(3) .law-item:nth-child(3) p", "laws.law5Text"],
        [".law-item strong", "laws.openDocument"],
        [".history-card h3", "laws.sideTitle"],
        [".history-card p", "laws.sideText"],
        [".history-menu h3", "common.aboutUs"]
    ],
    teachers: [
        [".page-hero .breadcrumb", "teachers.heroBreadcrumb"],
        [".page-hero h2", "teachers.heroTitle"],
        [".page-hero p", "teachers.heroText"],
        [".teachers-heading span", "teachers.headingEyebrow"],
        [".teachers-heading h2", "teachers.headingTitle"],
        [".director-profile h3", "teachers.directorName"],
        [".director-profile p", "teachers.directorTitle"],
        [".personnel-section:nth-of-type(2) .personnel-divider span", "teachers.groupDistrict"],
        [".personnel-section:nth-of-type(3) .personnel-divider span", "teachers.groupSubdistrict"],
        [".personnel-section:nth-of-type(2) .person-card:nth-child(1) h3", "teachers.person1Name"],
        [".personnel-section:nth-of-type(2) .person-card:nth-child(1) p", "teachers.person1Role"],
        [".personnel-section:nth-of-type(2) .person-card:nth-child(2) h3", "teachers.person2Name"],
        [".personnel-section:nth-of-type(2) .person-card:nth-child(2) p", "teachers.person2Role"],
        [".personnel-section:nth-of-type(2) .person-card:nth-child(2) p", "teachers.person2tag"],
        [".personnel-section:nth-of-type(2) .person-card:nth-child(3) h3", "teachers.person3Name"],
        [".personnel-section:nth-of-type(2) .person-card:nth-child(3) p", "teachers.person3Role"],
        [".personnel-section:nth-of-type(3) .person-card:nth-child(1) h3", "teachers.person4Name"],
        [".personnel-section:nth-of-type(3) .person-card:nth-child(1) p", "teachers.person4Role"],
        [".personnel-section:nth-of-type(3) .person-card:nth-child(2) h3", "teachers.person5Name"],
        [".personnel-section:nth-of-type(3) .person-card:nth-child(2) p", "teachers.person5Role"],
        [".personnel-section:nth-of-type(3) .person-card:nth-child(3) h3", "teachers.person6Name"],
        [".personnel-section:nth-of-type(3) .person-card:nth-child(3) p", "teachers.person6Role"],
        [".personnel-section:nth-of-type(3) .person-card:nth-child(4) h3", "teachers.person7Name"],
        [".personnel-section:nth-of-type(3) .person-card:nth-child(4) p", "teachers.person7Role"],
        [".personnel-section:nth-of-type(3) .person-card:nth-child(5) h3", "teachers.person8Name"],
        [".personnel-section:nth-of-type(3) .person-card:nth-child(5) p", "teachers.person8Role"],
        [".personnel-section:nth-of-type(3) .person-card:nth-child(6) h3", "teachers.person9Name"],
        [".personnel-section:nth-of-type(3) .person-card:nth-child(6) p", "teachers.person9Role"]
    ],
    mission: [
        [".page-hero .breadcrumb", "mission.heroBreadcrumb"],
        [".page-hero h2", "mission.heroTitle"],
        [".page-hero p", "mission.heroText"],
        [".history-content > .history-heading h2", "mission.headingTitle"],
        [".vision-box span", "mission.visionLabel"],
        [".vision-box p", "mission.visionText"],
        [".mission-heading h2", "mission.missionHeading"],
        [".mission-item:nth-child(1) h3", "mission.mission1Title"],
        [".mission-item:nth-child(1) p", "mission.mission1Text"],
        [".mission-item:nth-child(1) .mission-note", "mission.mission1Note"],
        [".mission-item:nth-child(2) h3", "mission.mission2Title"],
        [".mission-item:nth-child(2) p", "mission.mission2Text"],
        [".mission-item:nth-child(3) h3", "mission.mission3Title"],
        [".mission-item:nth-child(3) p", "mission.mission3Text"],
        [".history-card h3", "mission.heroTitle"],
        [".history-card p", "mission.sideText"],
        [".history-menu h3", "common.aboutUs"]
    ],
    news: [
        [".page-hero .breadcrumb", "news.heroBreadcrumb"],
        [".page-hero h2", "news.heroTitle"],
        [".page-hero p", "news.heroText"],
        [".news-toolbar h2", "news.listTitle"],
        [".news-pill", "news.featured"],
        [".news-feature h3", "news.featureTitle"],
        [".news-feature p", "news.featureText"],
        [".news-feature .news-meta", "news.featureMeta"],
        [".read-more", "common.readMore"],
        [".news-row:nth-child(1) .news-pill", "news.row1Badge"],
        [".news-row:nth-child(1) h3", "news.row1Title"],
        [".news-row:nth-child(1) p", "news.row1Text"],
        [".news-row:nth-child(1) .news-meta", "news.row1Meta"],
        [".news-row:nth-child(2) .news-pill", "news.row2Badge"],
        [".news-row:nth-child(2) h3", "news.row2Title"],
        [".news-row:nth-child(2) p", "news.row2Text"],
        [".news-row:nth-child(2) .news-meta", "news.row2Meta"],
        [".news-row:nth-child(3) .news-pill", "news.row3Badge"],
        [".news-row:nth-child(3) h3", "news.row3Title"],
        [".news-row:nth-child(3) p", "news.row3Text"],
        [".news-row:nth-child(3) .news-meta", "news.row3Meta"],
        [".news-side-box:nth-child(1) h3", "common.newsCategory"],
        [".news-side-box:nth-child(2) h3", "common.latestNews"]
    ],
    jobs: [
        [".page-hero .breadcrumb", "jobs.heroBreadcrumb"],
        [".page-hero h2", "jobs.heroTitle"],
        [".page-hero p", "jobs.heroText"],
        [".news-toolbar h2", "jobs.listTitle"],
        [".job-card:nth-child(1) .job-status", "jobs.statusOpen"],
        [".job-card:nth-child(2) .job-status", "jobs.statusOpen"],
        [".job-card:nth-child(3) .job-status", "jobs.statusClosed"],
        [".job-card:nth-child(1) h3", "jobs.job1Title"],
        [".job-card:nth-child(1) p", "jobs.job1Text"],
        [".job-card:nth-child(1) .job-meta span:nth-child(1)", "jobs.job1Meta1"],
        [".job-card:nth-child(1) .job-meta span:nth-child(2)", "jobs.job1Meta2"],
        [".job-card:nth-child(2) h3", "jobs.job2Title"],
        [".job-card:nth-child(2) p", "jobs.job2Text"],
        [".job-card:nth-child(2) .job-meta span:nth-child(1)", "jobs.job2Meta1"],
        [".job-card:nth-child(2) .job-meta span:nth-child(2)", "jobs.job2Meta2"],
        [".job-card:nth-child(3) h3", "jobs.job3Title"],
        [".job-card:nth-child(3) p", "jobs.job3Text"],
        [".job-card:nth-child(3) .job-meta span:nth-child(1)", "jobs.job3Meta1"],
        [".job-card:nth-child(3) .job-meta span:nth-child(2)", "jobs.job3Meta2"],
        [".job-card:nth-child(1) .read-more", "common.details"],
        [".job-card:nth-child(2) .read-more", "common.details"],
        [".job-card:nth-child(3) .read-more", "jobs.viewAnnouncement"],
        [".news-side-box:nth-child(1) h3", "common.newsCategory"],
        [".news-side-box:nth-child(2) h3", "common.commonDocs"],
        [".news-side-box:nth-child(2) p:nth-child(2)", "jobs.doc1"],
        [".news-side-box:nth-child(2) p:nth-child(3)", "jobs.doc2"],
        [".news-side-box:nth-child(2) p:nth-child(4)", "jobs.doc3"]
    ],
    procurement: [
        [".page-hero .breadcrumb", "procurement.heroBreadcrumb"],
        [".page-hero h2", "procurement.heroTitle"],
        [".page-hero p", "procurement.heroText"],
        [".news-toolbar h2", "procurement.listTitle"],
        [".procurement-table th:nth-child(1)", "procurement.tableDate"],
        [".procurement-table th:nth-child(2)", "procurement.tableNo"],
        [".procurement-table th:nth-child(3)", "procurement.tableItem"],
        [".procurement-table th:nth-child(4)", "procurement.tableType"],
        [".procurement-table th:nth-child(5)", "procurement.tableStatus"],
        [".procurement-table tbody tr:nth-child(1) td:nth-child(1)", "procurement.row1Date"],
        [".procurement-table tbody tr:nth-child(1) td:nth-child(2)", "procurement.row1No"],
        [".procurement-table tbody tr:nth-child(1) td:nth-child(3)", "procurement.row1Item"],
        [".procurement-table tbody tr:nth-child(1) td:nth-child(4)", "procurement.row1Type"],
        [".procurement-table tbody tr:nth-child(1) .table-status", "procurement.row1Status"],
        [".procurement-table tbody tr:nth-child(2) td:nth-child(1)", "procurement.row2Date"],
        [".procurement-table tbody tr:nth-child(2) td:nth-child(2)", "procurement.row2No"],
        [".procurement-table tbody tr:nth-child(2) td:nth-child(3)", "procurement.row2Item"],
        [".procurement-table tbody tr:nth-child(2) td:nth-child(4)", "procurement.row2Type"],
        [".procurement-table tbody tr:nth-child(2) .table-status", "procurement.row2Status"],
        [".procurement-table tbody tr:nth-child(3) td:nth-child(1)", "procurement.row3Date"],
        [".procurement-table tbody tr:nth-child(3) td:nth-child(2)", "procurement.row3No"],
        [".procurement-table tbody tr:nth-child(3) td:nth-child(3)", "procurement.row3Item"],
        [".procurement-table tbody tr:nth-child(3) td:nth-child(4)", "procurement.row3Type"],
        [".procurement-table tbody tr:nth-child(3) .table-status", "procurement.row3Status"],
        [".procurement-table tbody tr:nth-child(4) td:nth-child(1)", "procurement.row4Date"],
        [".procurement-table tbody tr:nth-child(4) td:nth-child(2)", "procurement.row4No"],
        [".procurement-table tbody tr:nth-child(4) td:nth-child(3)", "procurement.row4Item"],
        [".procurement-table tbody tr:nth-child(4) td:nth-child(4)", "procurement.row4Type"],
        [".procurement-table tbody tr:nth-child(4) .table-status", "procurement.row4Status"],
        [".news-side-box:nth-child(1) h3", "common.newsCategory"],
        [".news-side-box:nth-child(2) h3", "common.announcementTypes"],
        [".news-side-box:nth-child(2) p:nth-child(2)", "procurement.type1"],
        [".news-side-box:nth-child(2) p:nth-child(3)", "procurement.type2"],
        [".news-side-box:nth-child(2) p:nth-child(4)", "procurement.type3"],
        [".news-side-box:nth-child(2) p:nth-child(5)", "procurement.type4"]
    ],
    contact: [
        [".contact-breadcrumb .container", "contact.breadcrumb"],
        [".contact-info .history-heading h2", "contact.headingTitle"],
        [".contact-info h3", "common.schoolName"],
        [".contact-block:nth-of-type(2) strong", "contact.locationLabel"],
        [".contact-block:nth-of-type(2) p", "contact.locationText"],
        [".contact-mini:nth-child(1) span", "contact.addressLabel"],
        [".contact-mini:nth-child(1) strong", "contact.addressLine"],
        [".contact-mini:nth-child(1) p", "contact.addressText"],
        [".contact-mini:nth-child(2) span", "contact.hoursLabel"],
        [".contact-mini:nth-child(2) strong", "contact.hoursDay"],
        [".contact-mini:nth-child(2) p", "contact.hoursTime"],
        [".contact-block:nth-of-type(4) strong", "contact.channelLabel"],
        [".contact-block:nth-of-type(4) p:nth-of-type(1)", "contact.phone"],
        [".contact-block:nth-of-type(4) p:nth-of-type(2)", "contact.email"],
        [".required-note", "contact.requiredNote"],
        [".contact-form button", "contact.submit"]
    ]
};

const inputBindings = {
    index: [[".search-box input", "index.searchPlaceholder"]],
    news: [[".news-filter input", "news.searchPlaceholder"]],
    jobs: [[".news-filter input", "jobs.searchPlaceholder"]],
    procurement: [[".news-filter input", "procurement.searchPlaceholder"]]
};

const getValue = (lang, path) => {
    const [section, key] = path.split(".");
    return translations[lang]?.[section]?.[key] ?? translations.th?.[section]?.[key] ?? "";
};

const setText = (selector, path, lang) => {
    document.querySelectorAll(selector).forEach((element) => {
        const value = getValue(lang, path);
        if (value) element.textContent = value;
    });
};

const setPlaceholder = (selector, path, lang) => {
    document.querySelectorAll(selector).forEach((element) => {
        const value = getValue(lang, path);
        if (value) element.placeholder = value;
    });
};

const prepareTopStrip = () => {
    const container = document.querySelector(".top-strip .container");
    if (!container) return;

    container.innerHTML = `
        <span data-i18n="schoolName"></span>
        <div class="top-strip-actions">
            <span data-i18n="slogan"></span>
            <div class="language-switcher" aria-label="เลือกภาษา">
                <button class="language-btn" type="button" data-lang-switch="th" aria-label="ภาษาไทย">🇹🇭</button>
                <button class="language-btn" type="button" data-lang-switch="en" aria-label="English">🇬🇧</button>
            </div>
        </div>
    `;
};

const translateDataAttributes = (lang) => {
    const page = document.body.dataset.page || "index";

    document.querySelectorAll("[data-i18n]").forEach((element) => {
        const key = element.dataset.i18n;
        const value = translations[lang]?.[page]?.[key] || translations[lang]?.common?.[key] || translations.th?.[page]?.[key] || translations.th?.common?.[key];
        if (value) element.textContent = value;
    });

    document.querySelectorAll("[data-i18n-placeholder]").forEach((element) => {
        const key = element.dataset.i18nPlaceholder;
        const value = translations[lang]?.[page]?.[key] || translations[lang]?.common?.[key] || translations.th?.[page]?.[key] || translations.th?.common?.[key];
        if (value) element.placeholder = value;
    });
};

const updateContactLabels = (lang) => {
    if ((document.body.dataset.page || "index") !== "contact") return;

    document.querySelectorAll(".contact-form label").forEach((label) => {
        const input = label.querySelector("input, textarea");
        const required = label.querySelector("span");
        const field = input?.name;
        const key = {
            name: "nameLabel",
            email: "emailLabel",
            subject: "subjectLabel",
            message: "messageLabel"
        }[field];

        if (!key) return;

        const text = translations[lang].contact[key];
        label.textContent = `${text} `;
        if (required) label.appendChild(required);
        if (input) label.appendChild(input);
    });
};

const switchLanguage = (lang) => {
    const current = translations[lang] ? lang : "th";
    const page = document.body.dataset.page || "index";

    document.documentElement.lang = current;
    document.title = translations[current]?.[page]?.pageTitle || translations[current].index.pageTitle;

    translateDataAttributes(current);
    commonBindings.forEach(([selector, path]) => {
        if (page === "index" && selector.startsWith(".footer-grid > div:nth-child(3)")) return;
        setText(selector, path, current);
    });
    (pageBindings[page] || []).forEach(([selector, path]) => setText(selector, path, current));
    (inputBindings[page] || []).forEach(([selector, path]) => setPlaceholder(selector, path, current));
    updateContactLabels(current);

    document.querySelectorAll(".history-menu a:nth-of-type(1)").forEach((element) => element.textContent = translations[current].common.history);
    document.querySelectorAll(".history-menu a:nth-of-type(2)").forEach((element) => element.textContent = translations[current].common.authority);
    document.querySelectorAll(".history-menu a:nth-of-type(3)").forEach((element) => element.textContent = translations[current].common.missionVision);
    document.querySelectorAll(".history-menu a:nth-of-type(4)").forEach((element) => element.textContent = translations[current].common.staff);
    document.querySelectorAll(".history-menu a:nth-of-type(5)").forEach((element) => element.textContent = translations[current].common.law);
    document.querySelectorAll(".news-side-box:nth-child(1) a:nth-of-type(1)").forEach((element) => element.textContent = translations[current].common.publicNews);
    document.querySelectorAll(".news-side-box:nth-child(1) a:nth-of-type(2)").forEach((element) => element.textContent = translations[current].common.jobsNews);
    document.querySelectorAll(".news-side-box:nth-child(1) a:nth-of-type(3)").forEach((element) => element.textContent = translations[current].common.procurement);

    document.querySelectorAll("[data-lang-switch]").forEach((button) => {
        const isActive = button.dataset.langSwitch === current;
        button.classList.toggle("is-active", isActive);
        button.setAttribute("aria-pressed", String(isActive));
    });

    localStorage.setItem("siteLanguage", current);
};

prepareTopStrip();

document.querySelectorAll("[data-lang-switch]").forEach((button) => {
    button.addEventListener("click", () => switchLanguage(button.dataset.langSwitch));
});

switchLanguage(localStorage.getItem("siteLanguage") || "th");
